Enable native MySQL authentication on initial Rocky start

diff --git a/tests/common/prepare-ansible-roles b/tests/common/prepare-ansible-roles
--- a/tests/common/prepare-ansible-roles
+++ b/tests/common/prepare-ansible-roles
@@ -11,6 +11,7 @@ requirements_file=$1
 roles_dir=roles
 percona_dir="${roles_dir}/artefactual.percona"
 handler_file="${percona_dir}/handlers/main.yml"
+configure_centos_file="${percona_dir}/tasks/configure-centos.yml"
 secure_file="${percona_dir}/tasks/secure.yml"
 memcached_file="${roles_dir}/artefactual.memcached/tasks/main.yml"
 archivematica_src_dir="${roles_dir}/artefactual.archivematica-src"
@@ -23,6 +24,36 @@ if grep --quiet 'state=restarted' "$handler_file"; then
     sed --in-place 's/state=restarted/state=started/' "$handler_file"
 elif ! grep --quiet 'state=started' "$handler_file"; then
     echo "Could not adjust the Percona MySQL restart handler" >&2
+    exit 1
+fi
+
+percona_service_task='- name: "Ensure that percona is running and enabled"'
+percona_sysconfig_task='- name: "Enable mysql_native_password on initial Red Hat start"'
+if grep --fixed-strings --quiet -- \
+        "$percona_sysconfig_task" "$configure_centos_file"
+then
+    :
+elif grep --fixed-strings --quiet -- \
+        "$percona_service_task" "$configure_centos_file"
+then
+    sed --in-place \
+        '/^- name: "Ensure that percona is running and enabled"$/i\
+- name: "Enable mysql_native_password on initial Red Hat start"\
+  lineinfile:\
+    path: "/etc/sysconfig/mysql"\
+    regexp: "^MYSQLD_OPTS="\
+    line: "MYSQLD_OPTS=--mysql-native-password=ON"\
+    create: true\
+    owner: "root"\
+    group: "root"\
+    mode: "0644"\
+  when:\
+    - mysql_version is version("8.4", ">=")\
+    - mysql_enable_legacy_authentication_plugin | default(false) | bool
+' \
+        "$configure_centos_file"
+else
+    echo "Could not configure Percona startup options for Red Hat systems" >&2
     exit 1
 fi
 
